### PR TITLE
Move modification for source inputs

### PR DESCRIPTION
**Pull request by Piit3r**
Hi, i am wondering if this modification is ok to you. Because i think it will be great to improve these inputs. Then we could config them as follow :
    {
        "name": "HDMI 1",
        "type": "SOURCE",
        "position": 1
    }

### CODE REVIEW

**Comment by vniehues** [comment]
Hey @Piit3r! 
Thanks for your pull-request! I'm afraid either I don't understand what you are trying to do or you don't understand how the plugin selects inputs.

The plugin only sends a series of inputs since the SaphiAPI doesn't support to directly set a source with 1 command. (Jointspace does but it's disabled in SaphiOS)
Because of that we need to have a "fixed point of entry" in the series. To achieve this fixed point I first start WatchTV, send Sources and then CursorDown. This ensures that the cursor is always at the same position. 
If we don't do that, the cursor will always start at the currently selected input. The problem is that the problem can not **know** what input is currently selected. 

Unfortunately, your changes (and your example) would make the plugin send "HDMI 1" to the TV which the TV would just ignore because it's not a valid "input key". A list of available input keys can be [found here](https://github.com/eslavnov/pylips/wiki/Input-key-(POST)).

Just in case the error is on me: Please tell me your thoughts behind the changes - If you have more information and this is indeed a valid change I will gladly accept the PR! 


btw: the config you posted works. When I use that config on my TV, HDMI 1 will select the hdmi1-input :)

**Comment by Piit3r** [comment]
Sure, i understand you technique.
But i searched a bit more, i found that we can send a body like this one to input/key :
`{
        "query": "HDMI 1"
}`
Found it on [availables commands in pylips](https://github.com/eslavnov/pylips/blob/a87adc37557c9a9765e4042e0dc460b82078274d/available_commands.json)
I cannot test it today but i'll do it tommorow!

And yes, what i've done is wrong. This is not 
`{
        "key": "HDMI 1"
}`
But "query"

How is it possible that this config select you the hdmi1? Does the hdmi1 just under TV channels for you?
Because this technique's problem is that we will not all have the same inputs..

**Comment by Piit3r** [comment]
Oh, my bad..
These "query" can only be sent using Google Assistant, so on AndroidTVs

**Comment by vniehues** [comment]
> These "query" can only be sent using Google Assistant, so on AndroidTVs

Yeah unfortunately Saphi lacks many features :/


> How is it possible that this config select you the hdmi1? Does the hdmi1 just under TV channels for you?
Because this technique's problem is that we will not all have the same inputs..

Thats not determined by the "name" attribute but by the "position" attribute.
To "test" it do the following (or do it mentally): 
1. start your TV
2. on your remote press the following buttons:
    1. WatchTV
    2. Sources
    3. CursorDown
3. you are now on "position 0".
    1. one to the left would be "position -1"
    2. one to the right would be "position 1"
4. on my TV, HDMI 1 is actually on "position 1" thats why it matches haha

the plugin only analyses what input type you have and makes sure to land on a fixed starting point for each type. 
after that it only checks the position and determines where to go (what to press). Finally it add a "confirm" command to the end of the list of calls.

**Comment by vniehues** [comment]
... or are your Inputs ordered vertically? :o that would be something i need to add an option for.

**Comment by Piit3r** [comment]
Oh yes, mine are vertically, that's why i didn't understood..

**Comment by vniehues** [comment]
Ohhh I didn't know thats possible. 
Can you please show a picture of that? 
Actually if you could provide several pictures that could help very much: 
1. A picture of your Input selection
2. A picture of your App selection
3. A picture of your Remote

With these I can make some adjustments to the plugin which should allow it to work with your tv

**Comment by Piit3r** [comment]
Here you go :
Sources
IMG_1676
NETFLIX

As you can see, even in App selection it will be cool to have a vertical position selection

**Comment by vniehues** [comment]
Sorry for the late answer! 
Thank you for the pictures. For the inputs I will implement a simple switch which will make the plugin use up/down instead of left/right. 

regarding the apps I need to do more work. 
I will probably add another property called "row" in which you can define the vertical position. 
It would then look like this: 

```
{
    "name": "DEEZER",
    "type": "APP",
    "position": 5,
    "row": 1
}
```

You can see that the position would be 5 instead of 6 and the row would be 1 instead of 2 because the first row/position is not 1 but 0. 

Do you think that these implementations would fit your needs?

**Comment by vniehues** [comment]
@Piit3r you should be able to install the latest version with the following command: 

```
sudo npm install -g homebridge-saphi-tv@beta
```

this will install the current beta version. 
You will be able to set vertical sources and multirow apps via the config-ui. 
Adding the row to the app is currently only possible manually. You can copy the following code for a reference:

```
{
    "name": "DEEZER",
    "type": "APP",
    "position": 5,
    "row": 1
}
```

**Comment by vniehues** [comment]
@Piit3r Did you have a chance to test the latest beta yet? :)

**Pull request closed without merging**
